name: battle_it_out
description: BattleItOut - Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  flutter_localizations:
    sdk: flutter
  path_provider:
  yaml: ^3.1.0
  cupertino_icons: ^1.0.2
  tuple: ^2.0.0

dev_dependencies:
  sqflite_common_ffi:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/templates/
    - assets/database/
    - assets/database/localisation/
