name: battle_it_out
description: BattleItOut - Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.20
  flutter_localizations:
    sdk: flutter
  path_provider:
  yaml: ^3.1.2
  cupertino_icons: ^1.0.6
  tuple: ^2.0.2
  uuid: ^4.3.3
  collection: ^1.18.0
  path: ^1.8.3
  editable: ^2.0.0
  deepcopy: ^1.1.2
  equatable: ^2.0.5
  provider: ^6.1.1
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon_cropped.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/test/
    - assets/localisation/
