name: battle_it_out
description: BattleItOut - Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  sqlite3_flutter_libs: ^0.5.15
  flutter_localizations:
    sdk: flutter
  path_provider:
  yaml: ^3.1.2
  cupertino_icons: ^1.0.2
  tuple: ^2.0.0
  uuid: ^3.0.7
  collection: ^1.17.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/database/
    - assets/database/localisation/
