name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Install dependencies
        run: flutter pub get

      #      - name: Verify formatting
      #        run: dart format --output=none .

      - name: Analyze project source
        run: flutter analyze .

      - name: Run tests
        run: flutter test

#      - name: Build package
#        run: flutter build apk
#
#      - uses: actions/upload-artifact@v1
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk
